version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn tech_demo.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=tech_demo.settings

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: stock_data
      MYSQL_USER: sayali97
      MYSQL_PASSWORD: Sugandha1274*
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A tech_demo worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - web
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=tech_demo.settings
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A tech_demo beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - web
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=tech_demo.settings
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  # flower:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   command: celery -A tech_demo flower --port=5555
  #   ports:
  #     - "5555:5555"
  #   depends_on:
  #     - redis
  #     - db
  #     - celery_worker
  #   environment:
  #     - DJANGO_SETTINGS_MODULE=tech_demo.settings
  #     - CELERY_BROKER_URL=redis://redis:6379/0
  #     - CELERY_RESULT_BACKEND=redis://redis:6379/0

volumes:
  mysql_data:
  celery_beat_data:

