apiVersion: batch/v1
kind: Job
metadata:
  name: django-test-job
spec:
  template:
    spec:
      containers:
      - name: django
        image: sayalisa2li7/backend_techdemo:2.5  # Use your Django image
        command: ["python3", "manage.py", "fetch_stock_data"]  # Your management command
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: tech_demo.settings
        - name: DATABASE_URL
          value: mysql://sayali97:Sugandha1274*@db:3306/stock_data
      restartPolicy: OnFailure
