# Generated by Django 2.2.12 on 2024-07-27 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='stockpricedata',
            table='stock_prices_data',
        ),
    ]
