# Generated by Django 3.2.25 on 2024-07-30 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_dailyclosingpricereport_pricechangepercentagereport_topgainerslosersreport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topgainerslosersreport',
            options={'ordering': ['-date', 'price_change_percentage']},
        ),
        migrations.AlterField(
            model_name='topgainerslosersreport',
            name='report_type',
            field=models.CharField(choices=[('Gainer', 'Gainer'), ('Loser', 'Loser')], max_length=10),
        ),
    ]
