# Generated by Django 3.2.25 on 2024-07-30 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20240730_0613'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topgainerslosersreport',
            options={'verbose_name': 'Top Gainers/Losers Report', 'verbose_name_plural': 'Top Gainers/Losers Reports'},
        ),
        migrations.RemoveField(
            model_name='topgainerslosersreport',
            name='report_type',
        ),
        migrations.AddField(
            model_name='topgainerslosersreport',
            name='is_gainer',
            field=models.BooleanField(null=True),
        ),
        migrations.AddIndex(
            model_name='topgainerslosersreport',
            index=models.Index(fields=['date'], name='myapp_topga_date_ac2c19_idx'),
        ),
        migrations.AddIndex(
            model_name='topgainerslosersreport',
            index=models.Index(fields=['ticker'], name='myapp_topga_ticker_8a6864_idx'),
        ),
        migrations.AddIndex(
            model_name='topgainerslosersreport',
            index=models.Index(fields=['is_gainer'], name='myapp_topga_is_gain_fd7360_idx'),
        ),
    ]
